name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build deps
      run: sudo apt-get install mm-common libtool rake ruby

    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: built
        FOLDER: build
